<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <AssemblyName>ClaudeNim.Aot</AssemblyName>
    <RootNamespace>ClaudeNim.Aot</RootNamespace>
    <OutputType>Exe</OutputType>
    <IsPublishable>true</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Refit" />
    <PackageReference Include="Refit.HttpClientFactory" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ClaudeNim.Aot.Tests" />
    <InternalsVisibleTo Include="ClaudeNim.Aot.Benchmarks" />
  </ItemGroup>

</Project>
